#cloud-config
package_update: true
package_upgrade: true
packages:
  - netcat-openbsd
  - nmap
  - curl
  - python3
  - python3-pip

runcmd:
  - [mkdir, -p, /opt/attack-scripts]
  - [mkdir, -p, /home/ubuntu/logs]
  - [chown, -R, ubuntu:ubuntu, /home/ubuntu/logs]
  - [pip3, install, requests]

final_message: "ATTACKER VM base configuration complete"