#cloud-config
package_update: true
package_upgrade: true
packages:
  - python3
  - python3-pip
  - ufw
  - htop
  - net-tools
  - tcpdump

# Solo configurazione di sistema, gli script vengono copiati separatamente
runcmd:
  - [systemctl, daemon-reload]
  - [ufw, --force, reset]
  - [ufw, default, deny, incoming]
  - [ufw, default, allow, outgoing]
  - [ufw, allow, OpenSSH]
  - [ufw, allow, 9000/tcp]
  - [ufw, allow, 8080/tcp]
  - [ufw, --force, enable]

final_message: "TARGET VM base configuration complete"